### ISSUE TITLE
Error when using exportRecords()

### ISSUE THREAD

**Issue by dadrivr** [nutterb/redcapAPI#100]
I just installed the latest version of the redcapAPI package today from CRAN.  I'm getting the following error and warnings when using the `exportRecords()` function:

```exportRecords(rcon)
Error in `levels<-`(`*tmp*`, value = if (nl == nL) as.character(labels) else paste0(labels,  : 
  factor level [4] is duplicated
In addition: Warning messages:
1: In rbind(c("1", " Feet and inches (ft", " in) "), c(" 2", " Centimeters (cm)" :
  number of columns of result is not a multiple of vector length (arg 2)```

**Comment by tobadia** [comment]
Hi @dadrivr. I was actually gonna open an issue and propose a PR for what seems to be the exact same problem.
After investigating on my end it happens when the label of a radio or checkbox contains a comma, which is also the case in your example. Instead of splitting by `c(level, label)`, `makeRedcapFactor()` returns `c(level, label_part_1, label_part_2, ..., label_part_n)` for this element, with n corresponding to the number of items when the split is done at a comma.

@nutterb the PR is imminent if you want to go from there. Basically, replacing:
`coding <- strsplit(coding,',',perl=TRUE)``
with
`coding <- regmatches(coding, regexpr(",", coding), invert = TRUE)`

Everything else is unchanged

**Comment by nutterb** [comment]
PR appreciated and merged.
