### ISSUE TITLE
Dropdown lists are not converted to factor levels in fieldToVar()

### ISSUE THREAD

**Issue by tobadia** [nutterb/redcapAPI#104]
Hi @nutterb,

Apologies for raising another issue but I've stumbled across another thing related to `FieldToVar()`. When dealing with a dropdown list, `field_type <-
 meta_data$text_validation_type_or_show_slider_number[meta_data$field_name == field_base]` returns a string `"autocomplete"` and thus the following lines where `field_type`is reverted to the content of `meta_data$field_type` is skipped.

As a result, the switch statement at the end is ignoring the `dropdown = makeRedcapFactor(x = records[[i]], coding = meta_data$select_choices_or_calculations[meta_data$field_name == field_base], factors = factors)` section and `makeRedcapFactor` is never called on a dropdown list.

I have not completely figured out why `"autocomplete"` is retained over `meta_data$field_type` for dropdown lists and thus have refrained from altering your code into a PR.

Any hint appreciated! For the time being, I'll just be re-compiling from source with a very ugly "if autocomplete then dropdown" part but this is absolutely not the way to fix your code properly.

Thanks
Thomas

**Comment by nutterb** [comment]
Ugh, this update has been a travesty.

How big is the meta data with this autocomplete issue? Could you send me a copy of it to benjamin.nutter@gmail.com?

I have Friday off this week, and will see if I can squeeze in some debugging around painting.

**Comment by tobadia** [comment]
I can definitely do that. Will send that tomorrow morning when I'm back in
the office.
Really cool that you're this fast in following up, I greatly appreciate
your time and effort in maintaining and developing this package!

**Comment by nutterb** [comment]
I figured out why it retains `text_validation_type_or_show_slider_number` over `field_type`.  The initial check looks at the text validation.  I chose to do this because text fields (dates, phone numbers, zip codes) all show "text" in the `field_type`, so you have to go to the text validation to figure out what type it is.  For some reason, I chose to start at text validation, and if it was `NA`, go back to `field_type`.  I've reversed this, hoping it makes more sense to start with field type and go to `text_validation` if it is a text field.  

I think this will be more robust for slider fields.  I don't know what exactly it will do to signature fields, though it looks like they get ignored in the same way file fields do.  So probably not an issue.
