### ISSUE TITLE
exportRecords() not exporting [form]_complete var

### ISSUE THREAD

**Issue by afleishman** [nutterb/redcapAPI#106]
The `exportRecords()` function isn't exporting the [form]_complete variable. The [form]_complete variable appears when I run the `exportFieldNames()` function. It also doesn't work when I try to specify `exportRecords(rcon, field = 'form_complete')`... I get the following error when I try to pull the field...

`Error in exportRecords(rcon, field = "[form]_complete") : 
  1 assertions failed:
 `*` The following are not valid field names: [form]_complete`

I'm using `R version 3.4.3` and `redcapAPI version 2.0`.

**Comment by nutterb** [comment]
I got a report via e-mail of this issue a week or so ago and just patched it over the weekend.  It hasn't hit CRAN yet, but is available at `devtools::install_github("nutterb/redcapAPI", ref = "devel")`

So sorry for the inconvenience.

**Comment by afleishman** [comment]
No problem at all! Thanks.

**Comment by januz** [comment]
I saw this issue while trying to solve a colleagues' problem who experienced the same issue (i.e., `[form]_complete`-fields not being exported). 

Funnily enough, I afterwards ran into a what seemed to be the same problem at first: I couldn't export data, when there were `[form]_complete`-fields in the `fields` argument of `exportRecords()`. An export of the whole data frame included the fields, so I now wonder---is it generally not possible to specifically select `[form]_complete` fields while exporting? Is that due to them being special fields not defined in the data dictionary? Does the REDCap API allow it?

We need to filter by these variables, and the whole data frame is gigantic, so it takes way longer to first export the whole data frame, then do the filtering locally.

**Comment by nutterb** [comment]
There are two sections of relevant code for this.  

[https://github.com/nutterb/redcapAPI/blob/devel/R/exportRecords.R#L263-L270](This section) is the initial check that all of the variables in the `fields` argument exist in the meta data.  It casts an error if any field isn't (as you've noticed).

[https://github.com/nutterb/redcapAPI/blob/devel/R/exportRecords.R#L308-L316](The second) piece of code determines which `[form]_complete` fields get included.  It identifies the forms associated for any variables in `fields`, and attaches the `[form]_complete` fields just for those forms. 

So, at present, if you need a `[form]_complete` field, you need to include at least one field from that form.  Hopefully that will get your colleague started.

I'm open to changing this behavior.  I can see the value of being able to extract a `[form]_complete` field without any of it's fields.  But I want to think through the right way to address it.  I will open (and tag you in) a new issue that works out the right approach.  If you have thoughts or opinions on how this ought to be handled, they'd be greatly appreciated.
