### ISSUE TITLE
Should the record ID column be assumed to be a character value?

### ISSUE THREAD

**Issue by nutterb** [nutterb/redcapAPI#118]
@wibeasley, I'm curious what you think about this one.  I got an e-mail describing a problem where the ID numbers 1234567.5 were being read in as 1234567.  It turns out the value was being read, but printed without the decimal because it was being read as a number.

Is it safe to assume that ID fields can always be read a characters?  I have a strong belief this is true (because, strictly speaking, they are categorical), but I don't want to commit that here if that isn't universally accepted.

**Comment by wibeasley** [comment]
> Is it safe to assume that ID fields can always be read a characters?

* In some sense, 'yes', since REDCap stores everything as a string in the [EAV](https://en.wikipedia.org/wiki/Entity%E2%80%93attribute%E2%80%93value_model) table, `redcap_data` (as you know).

* But if R ever converts it to a float/integer (before converting it back to a string), the ~15 digit limitation of a float could truncate the value and drop some characters.  Is there ever a time when `IDs` isn't already a character?

https://github.com/nutterb/redcapAPI/blob/63651ddcc0b102f523f5702dcc0fde4f333340e9/R/exportRecords.R#L427


* I think this portion of your code is smart, that you don't use something like `utils::read_csv()` for the IDs, so the values are never cast to something they shouldn't be.

https://github.com/nutterb/redcapAPI/blob/63651ddcc0b102f523f5702dcc0fde4f333340e9/R/exportRecords.R#L421-L423

**Comment by nutterb** [comment]
Good to know im not crazy. I will force the record ids to be characters.

Although I do use `read.csv` for the record ids. Its a couple lines after what you linked to. But im glad you pointed them out, or I wouldnt have thought to change those too.

**Comment by nutterb** [comment]
Implemented for version 2.2
