### ISSUE TITLE
Multiple warnings generated on exportRecords()

### ISSUE THREAD

**Issue by kylerove** [nutterb/redcapAPI#129]
When I call exportRecords against a project, I get multiple warning messages. Could this have to do with unrecognized character entities like �? I found a few lurking in some text fields for a few records and removed them. # of warning went down, but 14 still persist. I "seem" to have a complete returned data.table, but with the warnings, not sure of data integrity.

```
> warnings()
Warning messages:
1: In structure(x, label = label, class = c("labelled", class(x)[!class(x) %in%  ... :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.
```

**Comment by nutterb** [comment]
I think you may have two different issues going on here.  The unrecognized characters will only affect your data integrity so far as you feel like you need the original contents.  If they contain things like curly quotes or emoji, that may depend on your particular application.  Unfortunately, I don't have the time available to me to study the issue and resolve it.

The structure warning looks like a warning caused by using a different version of R than that which was used to build `redcapAPI`.  This shouldn't be something you need to worry about.  I'll find where in the code I am using this and alter it.

**Comment by nutterb** [comment]
Found the issue in the `labelVector` package.  Am making the fix there.
