### ISSUE TITLE
is `missingSummary` a function that anyone is interested in?

### ISSUE THREAD

**Issue by nutterb** [nutterb/redcapAPI#47]
I had a researcher ask me to review a database from a randomized trial for missing values.  They were hoping to have a systematic way to identify which fields were missing rather than review charts manually.

One my first pass, I found that most of the missing values were due to fields that were never reached because of branching logic.  So I worked in a way to removed those "appropriately missing" fields, as well as a way to remove fields where there form was never opened.

I don't know if I'll ever use this function again though, or if it's of any value outside of this one case.  So I'm not sure it's appropriate to include it in the package.  What think ye?

**Comment by wibeasley** [comment]
Consider releasing it as a Gist, and announcing it in the Google Group.  I've seen that done (in non-REDCap situations) when the core might be valuable to someone else, but you don't want to put in the time to make it robust to all the possible scenarios where it might be used.  You don't want to include a buggy, half-baked function into an otherwise stable package.

https://help.github.com/articles/about-gists/

https://help.github.com/articles/creating-gists/

**Comment by SteveLane** [comment]
I'd probably leave it out (or gist as an example). Hopefully we can get those designing their databases to not have redundant fields so that this sort of code is not necessary.

**Comment by nutterb** [comment]
I created a gist and linked to it in the README file.

thanks for the feedback.

**Comment by wibeasley** [comment]
@nutterb, are you going to announce it in the Google Group?  I suggest posting something there, and maybe asking if something should go in the wiki too.  I think this would give it a lot more attention than relying on someone to successfully search for that in Google, or get there via the repo readme.
