### ISSUE TITLE
Error in exportReports

### ISSUE THREAD

**Issue by SteveLane** [nutterb/redcapAPI#62]
The exportReports function is used to export data from reports built in REDCap. It calls another function internally, fieldToVar, which is a type-conversion function.

When trying to export a report, a user (W Campbell) found the following bug:

```{r}
rcon <- redcapConnection(redcap_url, project_token)
myReport <- exportReports(rcon, report_id = my_reports_id)

Error in if (grepl("date_", m$text_validation_type_or_show_slider_number) &&  : 
  missing value where TRUE/FALSE needed
```

**Comment by nutterb** [comment]
I'll see if I can diagnose this from the source code, but it's hard to test without access to a working REDCap API :(

Is there any chance Mr. Campbell would be willing to share his data dictionary and a screen shot of the report definition?

**Comment by nutterb** [comment]
Okay, I apologize.  That was an abysmally coded function.  You were right about where the problem was hitting.  I was confused at first because `exportReports` is almost an exact copy of `exportRecords`, so it didn't make sense to me that it would fail at `fieldToVar`.  But it turns out in `exportRecords`, I've already pared down the vector of inputs going into `fieldToVar` to just those variables in the meta data.  

After getting the right subset there, I found that the problem reared it's head two or three more times down the line.  I think I might need to try a rewrite and see if I can simplify the code and speed it up a little.  Once I get `pixiedust` updated, I might come back and spend a month or so on redcap.

Anyway, please give the `development` branch a go and let me know if it works for you.

**Comment by SteveLane** [comment]
Yeah, I found it a couple of times, but didn't get time to fix it before you! Nice work, it works great. Would you like me to merge the changes into master? I'll update the version number and news as well?

**Comment by nutterb** [comment]
It would be great if you could do that.  Thanks for tracking down the error.

**Comment by SteveLane** [comment]
Updated to v1.3.2

**Comment by nkarduri** [comment]
I'm still seeing the same issue -   I installed the package today 

library(redcapAPI) #Load the package into the current R session.
> rcon <- redcapConnection(url="XXXXXXXXX/redcap/api/", token="XXXXXXXXXXXXXXXXX")
> output <-  exportReports(rcon,report_id=3383)
Error in if (grepl("date_", m$text_validation_type_or_show_slider_number) &&  : 
  missing value where TRUE/FALSE needed

Could you please tell me how to fix this problem, Thanks.
