### ISSUE TITLE
How to get Label Headers while exporting data from RedCap?

### ISSUE THREAD

**Issue by kkayyala83** [nutterb/redcapAPI#73]
Hi, Thanks for the wonderful R package and it helped and saved me a lot of time. 
However, I need some help on achieving a simple task. When I export, the field names (i.e. column names) are raw, but I want actual labels. 

For e.g. I have a field name = obs_id (raw name), but its Label name is "Observation ID". So, when I export using API, my field name should be "Observation ID" instead of "obs_id".  

Any suggestions please? 
Thanks in advance for your help and support.

**Comment by nutterb** [comment]
The behavior you are describing is by fesign, because R doesn't recognize "Observation ID" as a valid column name (because of the space). The labels are stored as attributes in each vector. 

If you want to override the default behavior, you can use 

```r
names (data_frame) = Hmisc::label (data_frame, self = FALSE)
```

This assumes you have `label=TRUE` in your `exportRecords` call.

**Comment by nutterb** [comment]
@kkayyala83 did this help resolve your need?

**Comment by kkayyala83** [comment]
Hi Benjamin,

Sorry, I forgot to reply. No it did not help me.
I found one URl, https://penut-trial.org/rcapi/, where they are able to
extract Raw or Label Headers like below.
Raw or Label Headers:
raw label
[image: Inline image 3]

Please let me know if you know how to resolve this.

Thanks,
Krishna

**Comment by nutterb** [comment]
Krishna,

I was able to replicate the format you are seeking using the following code:

```r
library(redcapAPI)

rcon <- redcapConnection(url = 'URL',
                         token = 'TOKEN')

Data <- exportRecords(rcon, factors = FALSE, labels = TRUE, dates = FALSE)
# See the raw names
names(Data)

# Move the label attribute into the column name
# This is the one additional line of code needed to move the labels to the column name.
names(Data) <- Hmisc::label(Data, self = FALSE)

# See the new names
names(Data)
```

By way of explanation, when `exportRecords` retrieves your data with `labels = TRUE`, it assigns the variable label as an attribute to the vector in the data frame.  vector labels look a bit like this (Notice how the label appears above the output on the second printing):

```r
mtcars$mpg

 [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

Hmisc::label(mtcars$mpg) <- "Fuel Efficiency"
mtcars$mpg

Fuel Efficiency 
 [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4
```

These labels often have characters that are unsuitable for variable names and can be difficult to use in producing analyses, and since `redcapAPI` is intended to get to analysis as quickly as possible, it doesn't give the option of putting the labels in the column name position.  With the code above, however, it is possible to manually move the labels to be the column name, and only takes one additional line of code.

**Comment by kkayyala83** [comment]
Hi Benjamin,
Thanks for the help and it worked exactly like I wanted.
Krishna
