### ISSUE TITLE
date export shifts dates by one day

### ISSUE THREAD

**Issue by januz** [nutterb/redcapAPI#86]
when exporting data from a REDCap database date variables are shifted by -1 day. Is that a know issue? Searching for the issue, I found this:

https://openspecimen.atlassian.net/wiki/spaces/CAT/pages/86609837/Deploying+REDCap+plugin

**Comment by wibeasley** [comment]
@januz, is it shifting the dates just in the package?  Or does it shift the dates for you when you use Postman too?

Here's a troubleshooting guide that @nutterb and I wrote.  See the "Language Agnostic API" section.

https://cran.r-project.org/web/packages/REDCapR/vignettes/TroubleshootingApiCalls.html

**Comment by nutterb** [comment]
This is a new one that I haven't seen before. Could you try a manual export per the vignette in @wibeasley 's  comment and report if you get the same thing? You might also try using the REDCapR package.

**Comment by wibeasley** [comment]
@januz, if that doesn't identify the issue, could you 
1. report the timezones & locales of the REDCap server and any other similar settings/config you think could be relevant
1. confirm that these are *dates* and not *date-times*.
1. give a few examples of what it looks like in the database *vs* what it is returning

@nutterb, I'm just talking out loud...  I'm guessing our two packages will behave the same on this because (a) we don't do any calculations with time zones, (b) we both use httr+curl, and (c) our main read methods both use `utils::read.csv()` to convert from text to a data.frame.

* https://github.com/nutterb/redcapAPI/blob/master/R/exportRecords.R
* https://github.com/OuhscBbmc/REDCapR/blob/master/R/redcap-read-oneshot.R

Although I have experimented with `readr::read_csv()` in this [semi-hidden function](https://github.com/OuhscBbmc/REDCapR/blob/master/R/redcap-read-oneshot-eav.R) (that needs to be accessed like `REDCapR:::redcap_read_oneshot_eav()`).  @januz, try that function to give us some insight into where the shift is occurring.

**Comment by januz** [comment]
Thank you for your responses! I'll try to find some time to pin down the problem over the next days and report back.

**Comment by nutterb** [comment]
I'm getting the same responses from `redcapAPI` and from the Postman app.  Has there been any chatter about such a bug on the REDCap forums?

Another possibility is that you have dates represented in a Date/Time field.  If you use '2017-08-31 00:00:00', for example, and you live in the U.S., it's possible that your time zone is getting applied to the data.  Since we are five hours behind GMT, this could make the dates look like they are a day behind when viewed in R Studio.

**Comment by januz** [comment]
I tried to use Postman, but as the database is pretty huge (4500 cases, 3500 variables), the app crashes.

Here some more information on my situation:

- I'm in Germany, so the time zone of the server is UTC +2 (summer time). 
- the field is set as a date (Y-M-D)
- however, after importing to R, the column is formatted as POSIXct

**Comment by wibeasley** [comment]
@januz, thanks for that information.  I think the key is that it's being interpreted as a *date-time* instead of a *date*.  Could you
* give a few examples of what it looks like (a) in the database vs (b) what it is returning
* tell us if both the client and the server are UTC+2?  (Any chance the client's in a different time zone than the server, or where the cell was entered?)
* use the record filter in PostMan to limit to ~100 rows and just a few columns?

Building off of @nutterb's post, I'm wondering if there are only a few records in the field that are stored as date-times (and everything else is formatted like a date).  That could happen, especially if your input validation was activated after some records were already entered.

Assume a value like '2017-08-31 00:00:00' lived at the 43rd record (and the first 42 records were like '2017-08-31').  If you export the first 40 records (through either recapAPI or REDCapR), the `util:read.csv()` would convert that field into a date.  However if you export the first 45 records, both packages might convert it to a datetime/POSIXct.  The function [`type.convert()`](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/type.convert.html) is doing the real work.

The Postman results will be really helpful here.  It will show if the date shift is happening before or after the data get to R.

(@nutterb, I hope this is helpful and not getting in your way.)

**Comment by nutterb** [comment]
I don't think the formatting of any individual record is the issue.  `redcapAPI` reads in all date and datetime columns as characters and then coerces both of those to `POSIXct` types.  

Let's try this instead:  Please run the following code.  You an adjust your `records` element to the record ID's of a few of the record ID's in your project.  This will let us just look at a handful of values.  You'll also need to adjust the `fields` argument to include a few date and date/time fields.  

This output we get off of this call is what we receive from the API before `redcapAPI` does any work on it.  This will give us the full view of what the date values are from the UI, to the API export, to the finished product by `redcapAPI`

```
httr::POST(url = rcon$url,
           body = list(token = rcon$token, 
                       content = 'record',
                       format = 'csv', 
                       type = 'flat',
                       fields = 'field1,field2,field3',
                       records = '1,2,3,4,5'))
```

**Comment by januz** [comment]
I don't know what to tell you, but now exporting the dates works without shifting dates. I didn't do anything differently, so I'm a little lost what might have caused the problem earlier when it appeared consistently. Sorry that I cannot be more helpful :/

**Comment by nutterb** [comment]
possible cause...an unidentified setting in your environment that was cleared when you opened a clean session.

I'm also a fan of blaming solar flares and gremlins. glad it is working now.
